
STRELKA_VARIANT_CALLER = "strelka"
STARLING_VARIANT_CALLER = "starling"
DUPLICATION_FINDER = "duplication_finder"
PLATYPUS_VARIANT_CALLER = "platypus"
GENERIC_VARIANT_CALLER = "generic"

INCLUDE_ALTERNATE = "1"
EXCLUDE_ALTERNATE = "2"

SELECTION_METHOD_AF = "af"
SELECTION_METHOD_QUALITY = "quality"
SELECTION_METHOD_ARBITRARY = "arbitrary"
SELECTION_METHOD_ALLELE_CALLS = "allele_calls"